version: 2

models:
  - name: mart_booking_summary
    description: "Summary of bookings data"
    columns:
      - name: route_id
        description: "The unique identifier for a route"
        data_tests:
          - not_null
          - unique
      - name: total_bookings
        description: "Total number of bookings for the route"
        data_tests:
          - not_null

  - name: mart_staff_performance
    description: "Performance metrics for staff members"
    columns:
      - name: staff_id
        description: "The unique identifier for a staff member"
        data_tests:
          - not_null
          - unique
      - name: first_name
        description: "The first name of the staff member"
      - name: last_name
        description: "The last name of the staff member"
      - name: full_name
        description: "The full name of the staff member"
      - name: position
        description: "The position of the staff member"
      - name: hire_date
        description: "The hire date of the staff member"
      - name: total_bookings_handled
        description: "Total number of bookings handled by the staff member"
        data_tests:
          - not_null

  - name: mart_route_performance
    description: "Performance metrics for routes"
    columns:
      - name: route_id
        description: "The unique identifier for a route"
        data_tests:
          - not_null
          - unique
      - name: route_description
        description: "The concatenated origin and destination of the route"
      - name: distance
        description: "The distance of the route"
      - name: duration
        description: "The duration of the route"
      - name: total_bookings
        description: "Total number of bookings for the route"
        data_tests:
          - not_null

  - name: mart_customer_activity
    description: "Activity metrics for customers"
    columns:
      - name: customer_id
        description: "The unique identifier for a customer"
        data_tests:
          - not_null
          - unique
      - name: total_bookings
        description: "Total number of bookings made by the customer"
        data_tests:
          - not_null

  - name: mart_vehicle_utilization
    description: "Utilization metrics for vehicles"
    columns:
      - name: vehicle_id
        description: "The unique identifier for a vehicle"
        data_tests:
          - not_null
          - unique
      - name: total_bookings
        description: "Total number of bookings made using the vehicle"
        data_tests:
          - not_null
